__use_yte__: true

# Set yte vars
__variables__:
  mail: "'--mail-type=ALL --mail-user=benjamin.bromberg@tufts.edu --error=logs/"
  end_err_log_str: "_slurm_stderr.%j.%N.log'"

# Profile Settings
executor: slurm
jobs: 100
conda-frontend: conda
sdm: conda
default-resources:
  slurm_partition: "interactive"
  slurm_account: "default"
  runtime: 240 # TODO change to batch or mpi partition and 4320 min
  mem_mb: 32000
  cpus_per_task: 12

set-resources:
  datasets_download_genome:
    job-name: "'datasets_download_genome'"
    slurm_extra: ?mail + 'datasets/datasets_download_genome' + end_err_log_str
  unzip_genome:
    job-name: "'unzip_genome'"
    slurm_extra: ?mail + 'datasets/unzip_genome' + end_err_log_str
  salmon_decoys:
    job-name: "'salmon_decoys'"
    slurm_extra: ?mail + 'salmon/salmon_decoys' + end_err_log_str
  salmon_index:
    job-name: "'salmon_index'"
    slurm_extra: ?mail + 'salmon/salmon_index' + end_err_log_str
  create_gtf:
    job-name: "'create_gtf'"
    slurm_extra: ?mail + 'gffread/create_gtf' + end_err_log_str
  star_index:
    job-name: "'star_index'"
    slurm_extra: ?mail + 'star/star_index' + end_err_log_str
    mem_mb: 64000
