__use_yte__: true

# Set yte vars
__variables__:
  mail: "'--mail-type=ALL --mail-user=benjamin.bromberg@tufts.edu'"

# Profile Settings
executor: slurm
jobs: 100
conda-frontend: conda
sdm: conda
latency-wait: 120
default-resources:
  slurm_partition: "batch"
  slurm_account: "default"
  runtime: 4320 # TODO change to batch or mpi partition and 4320 min
  mem_mb: 32000
  cpus_per_task: 12
  slurm_extra: ?mail

set-resources:
  star_index:
    mem_mb: 64000
