__use_yte__: true

# Set yte vars
__variables__:
  mail: "'--mail-type=ALL --mail-user=benjamin.bromberg@tufts.edu'"

# Profile Settings
executor: slurm
jobs: 100
conda-frontend: conda
sdm: conda
default-resources:
  slurm_partition: "interactive"
  slurm_account: "default"
  runtime: 240 # TODO change to batch or mpi partition and 4320 min
  mem_mb: 32000
  cpus_per_task: 12

set-resources:
  datasets_download_genome:
    job-name: "'datasets_download_genome'"
    slurm_extra: ?f"{mail} + '--error=logs/datasets/datasets_download_genome_slurm_stderr.%j.%N.log'"
  unzip_genome:
  salmon_decoys:
    job-name: "'salmon_decoys'"
    slurm_extra: ?f"{mail} + '--error=logs/salmon/salmon_decoys_slurm_stderr.%j.%N.log'"
  salmon_index:
    job-name: "'salmon_index'"
    slurm_extra: ?f"{mail} + '--error=logs/salmon/salmon_index_slurm_stderr.%j.%N.log'"
  create_gtf:
    job-name: "'create_gtf'"
    slurm_extra: ?f"{mail} + '--error=logs/gffread/create_gtf_slurm_stderr.%j.%N.log'"
  star_index:
    job-name: "'star_index'"
    slurm_extra: ?f"{mail} + '--error=logs/star/star_index_slurm_stderr.%j.%N.log'"
    mem_mb: 64000
